/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CoreApiController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UsersController_updateMe"];
        trace?: never;
    };
    "/users/me/telegram-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UsersController_telegramLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["UsersController_unlinkTelegram"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_listPush"];
        put?: never;
        post: operations["UsersController_addPush"];
        delete: operations["UsersController_removePush"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/triggers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TriggersController_findAll"];
        put?: never;
        post: operations["TriggersController_create"];
        delete: operations["TriggersController_clear"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/triggers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TriggersController_findOne"];
        put?: never;
        post?: never;
        delete: operations["TriggersController_remove"];
        options?: never;
        head?: never;
        patch: operations["TriggersController_update"];
        trace?: never;
    };
    "/triggers/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TriggersController_test"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MetaController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["NotificationsController_findAll"];
        put?: never;
        post?: never;
        delete: operations["NotificationsController_clear"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["NotificationsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pinned-cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PinnedCitiesController_findAll"];
        put?: never;
        post: operations["PinnedCitiesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pinned-cities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["PinnedCitiesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminController_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminController_listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminController_getUser"];
        put?: never;
        post?: never;
        delete: operations["AdminController_deleteUser"];
        options?: never;
        head?: never;
        patch: operations["AdminController_updateUser"];
        trace?: never;
    };
    "/admin/triggers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AdminController_deleteTrigger"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponseDto: {
            /** @example ok */
            status: string;
        };
        /** @enum {string} */
        Role: "USER" | "ADMIN";
        ProfileResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            telegramChatId: string | null;
            telegramLinked: boolean;
            emailVerified: boolean;
            /** @example 22:00 */
            quietHoursStart: string | null;
            /** @example 07:00 */
            quietHoursEnd: string | null;
            /** @example Europe/Berlin */
            timezone: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        UpdateProfileDto: Record<string, never>;
        TelegramLinkDto: {
            /** @description Deep link the user opens to bind their chat */
            url: string;
            /** Format: uuid */
            token: string;
        };
        SuccessResultDto: {
            success: boolean;
        };
        PushSubscriptionResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uri */
            endpoint: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreatePushSubscriptionDto: Record<string, never>;
        DeletePushSubscriptionDto: Record<string, never>;
        RegisterDto: Record<string, never>;
        AuthResponseDto: {
            /** @description Short-lived JWT for the Authorization header */
            accessToken: string;
        };
        LoginDto: Record<string, never>;
        AuthUserDto: {
            /** Format: uuid */
            userId: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
        };
        VerifyEmailDto: Record<string, never>;
        VerifyEmailResultDto: {
            verified: boolean;
        };
        ResendVerificationResultDto: {
            sent: boolean;
        };
        CreateTriggerDto: Record<string, never>;
        /** @enum {string} */
        Metric: "TEMPERATURE" | "APPARENT_TEMP" | "WIND_SPEED" | "PRECIPITATION" | "HUMIDITY" | "SEVERE";
        /** @enum {string} */
        Operator: "GT" | "GTE" | "LT" | "LTE" | "EQ";
        TriggerConditionResponseDto: {
            /** Format: uuid */
            id: string;
            metric: components["schemas"]["Metric"];
            operator: components["schemas"]["Operator"];
            threshold: number;
            /** @description Position within the trigger */
            order: number;
            lastObservedValue: number | null;
            lastMatched: boolean | null;
        };
        /** @enum {string} */
        ConditionLogic: "AND" | "OR";
        /** @enum {string} */
        Channel: "TELEGRAM" | "EMAIL" | "WEB_PUSH";
        /** @enum {string} */
        TriggerState: "ARMED" | "FIRED";
        TriggerResponseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            city: string;
            latitude: number;
            longitude: number;
            conditions: components["schemas"]["TriggerConditionResponseDto"][];
            conditionLogic: components["schemas"]["ConditionLogic"];
            channels: components["schemas"]["Channel"][];
            /** @description Minutes before it can re-fire */
            cooldownMin: number;
            isActive: boolean;
            state: components["schemas"]["TriggerState"];
            /** Format: date-time */
            lastFiredAt: string | null;
            /** Format: date-time */
            lastEvaluatedAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        UpdateTriggerDto: Record<string, never>;
        CountResultDto: {
            count: number;
        };
        IdResultDto: {
            /** Format: uuid */
            id: string;
        };
        TriggerTestResultDto: {
            /** @description Channels the test event was published to */
            sent: components["schemas"]["Channel"][];
        };
        ApiLimitsDto: {
            maxTriggersPerUser: number;
            maxConditionsPerTrigger: number;
            maxPinnedCities: number;
            /** @description Seconds between test sends, counted per user not per trigger */
            testCooldownSec: number;
            minCooldownMin: number;
            maxCooldownMin: number;
            maxChannelsPerTrigger: number;
        };
        MetaResponseDto: {
            limits: components["schemas"]["ApiLimitsDto"];
        };
        /** @enum {string} */
        NotifStatus: "PENDING" | "SENT" | "FAILED";
        NotificationResponseDto: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Null once the originating trigger has been deleted
             */
            triggerId: string | null;
            channel: components["schemas"]["Channel"];
            status: components["schemas"]["NotifStatus"];
            /** @description The fired event as delivered — shape follows TriggerFiredEvent */
            payload: {
                [key: string]: unknown;
            };
            error: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        PinnedCityResponseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            country: string | null;
            /** @description Region or state */
            admin1: string | null;
            latitude: number;
            longitude: number;
            order: number;
            /** Format: date-time */
            createdAt: string;
        };
        CreatePinnedCityDto: Record<string, never>;
        AdminStatsDto: {
            users: number;
            verifiedUsers: number;
            admins: number;
            triggers: number;
            activeTriggers: number;
            pinnedCities: number;
            notifications: number;
            notificationsSent: number;
            notificationsFailed: number;
        };
        AdminUserDto: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            emailVerified: boolean;
            telegramLinked: boolean;
            triggerCount: number;
            notificationCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        AdminUserDetailDto: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            emailVerified: boolean;
            telegramLinked: boolean;
            quietHoursStart: string | null;
            quietHoursEnd: string | null;
            timezone: string | null;
            triggers: components["schemas"]["TriggerResponseDto"][];
            notificationCount: number;
            pinnedCityCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        UpdateUserDto: Record<string, never>;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    CoreApiController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponseDto"];
                };
            };
        };
    };
    UsersController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponseDto"];
                };
            };
        };
    };
    UsersController_telegramLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramLinkDto"];
                };
            };
        };
    };
    UsersController_unlinkTelegram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResultDto"];
                };
            };
        };
    };
    UsersController_listPush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushSubscriptionResponseDto"][];
                };
            };
        };
    };
    UsersController_addPush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePushSubscriptionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushSubscriptionResponseDto"];
                };
            };
        };
    };
    UsersController_removePush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeletePushSubscriptionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResultDto"];
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResultDto"];
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserDto"];
                };
            };
        };
    };
    AuthController_verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyEmailResultDto"];
                };
            };
        };
    };
    AuthController_resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResendVerificationResultDto"];
                };
            };
        };
    };
    TriggersController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["TriggerResponseDto"][];
                        total: number;
                        page: number;
                        limit: number;
                    };
                };
            };
        };
    };
    TriggersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTriggerDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerResponseDto"];
                };
            };
        };
    };
    TriggersController_clear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountResultDto"];
                };
            };
        };
    };
    TriggersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerResponseDto"];
                };
            };
        };
    };
    TriggersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResultDto"];
                };
            };
        };
    };
    TriggersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTriggerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerResponseDto"];
                };
            };
        };
    };
    TriggersController_test: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerTestResultDto"];
                };
            };
        };
    };
    MetaController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponseDto"];
                };
            };
        };
    };
    NotificationsController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["NotificationResponseDto"][];
                        total: number;
                        page: number;
                        limit: number;
                    };
                };
            };
        };
    };
    NotificationsController_clear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountResultDto"];
                };
            };
        };
    };
    NotificationsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResultDto"];
                };
            };
        };
    };
    PinnedCitiesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinnedCityResponseDto"][];
                };
            };
        };
    };
    PinnedCitiesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePinnedCityDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinnedCityResponseDto"];
                };
            };
        };
    };
    PinnedCitiesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResultDto"];
                };
            };
        };
    };
    AdminController_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStatsDto"];
                };
            };
        };
    };
    AdminController_listUsers: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AdminUserDto"][];
                        total: number;
                        page: number;
                        limit: number;
                    };
                };
            };
        };
    };
    AdminController_getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserDetailDto"];
                };
            };
        };
    };
    AdminController_deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResultDto"];
                };
            };
        };
    };
    AdminController_updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserDetailDto"];
                };
            };
        };
    };
    AdminController_deleteTrigger: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResultDto"];
                };
            };
        };
    };
}
